-- foreign.sql Jake Armendariz

--  #1
ALTER TABLE Markets
ADD FOREIGN KEY (managerID) REFERENCES Employees (empID)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

-- #2
ALTER TABLE Employees
ADD FOREIGN KEY (marketID) REFERENCES Markets (marketID)
ON DELETE CASCADE
ON UPDATE CASCADE ;

-- #3
ALTER TABLE ShoppingTrips
ADD FOREIGN KEY (marketID) REFERENCES Markets (marketID)
ON UPDATE CASCADE
ON DELETE SET NULL;
